### ISSUE TITLE
Gaia guardians don't despawn after Defeat/death, and magic wall doesn't dispell

### ISSUE THREAD

**Issue by VazkiMods** [VazkiMods/Botania#2]
Mod Loader
Fabric

Minecraft Version
Minecraft 1.20.1

Botania version
Botania 443

Modloader version
Fabric 0.15.9

Modpack info
None

The latest.log file
Other Information section for log

Issue description
Gaia Guardian(s) won't despawn after Player death, and stand still doing nothing, Ritual stays active after dying, and can't be re-joined, or ended

Steps to reproduce
Summon Gaia boss

Die to Gaia guardian

Gaia Guardian now don't despawn, can't be attacked or removed

Other information
Latest log, IDK how to use the offered sites

Edit: They disappear upon Re-Launching minecraft again, the bug only happens during the game

**Comment by Stuede1** [comment]
completed
